### PR TITLE
[bitnami/jasperreports] Fix SMTP settings for Jasperreports

### LINKED ISSUE #4677: [bitnami/jasperreports] Docker SMTP Configuration
### Name and Version

docker.io/bitnami/jasperreports:8

### What steps will reproduce the bug?

I am trying to configure the SMTP service through the environment variables in docker-compose.
image

### What is the expected behavior?

_No response_

### What do you see instead?

But when I schedule a send, I get the following error 
image

### Additional information

_No response_

### LINKED ISSUE #7296: [bitnami/jasperreports] Sending emails using Office365
### Name and Version

Jasper Reports 8.1.0

### What steps will reproduce the bug?

I am trying to configure Bitnami JasperReports image with Office365 email address for sending reports and scheduling them.
This link [https://community.jaspersoft.com/wiki/use-office-365-smtp-jasperreports-server](https://community.jaspersoft.com/wiki/use-office-365-smtp-jasperreports-server) describes that changes are required on (3) files: 
js.quartz.properties
applicationContext.xml
applicationContext-report-scheduling.xml

Changing the environment variables as described here [https://hub.docker.com/r/bitnami/jasperreports](https://hub.docker.com/r/bitnami/jasperreports) does not take into consideration those values:
```
mail.smtp.auth=true
mail.smtp.starttls.enable=true
```
I have tried to set the `JASPERREPORTS_SMTP_PROTOCOL` environment variable with the value "ssl" but still the `mail.smtp.auth=false` and `mail.smtp.starttls.enable` are not added to the javaMail bean in `applicationContext.xml`
and `applicationContext-report-scheduling.xml`

This issue says it will be automatically set, but I couldn't find that code and I'm not sure if takes affect: 

[https://github.com/bitnami/bitnami-docker-jasperreports/issues/81](https://github.com/bitnami/bitnami-docker-jasperreports/issues/81)

Would you please provide more information on how to set `mail.smtp.auth=true` and `mail.smtp.starttls.enable=true` values?

Thank you for the great support.

### What is the expected behavior?

Should be able to send emails using Office365.

### What do you see instead?

The value of `mail.smtp.auth` is still false.
`mail.smtp.starttls.enable` is not added to the context xml files.

### PR DESCRIPTION
**Pull request by grantemsley**
### Description of the change

Add "smtp" as a valid option for JASPERREPORTS_SMTP_PROTOCOL and make it the default. I'm not sure if 'ssl' and 'tls' are even valid options - every piece of documentation I've seen only shows it set to 'smtp'. But just in case, I have not removed the other options.

### Benefits

Makes it possible to get email working from JasperReports.

### Possible drawbacks

None

### Applicable issues

  - fixes #4677 
  - fixes #7296 

### Additional information

I've tested this on my own install and was finally able to get emails working with this change.

### CODE REVIEW

File: bitnami/jasperreports/8/debian-11/rootfs/opt/bitnami/scripts/libjasperreports.sh [hunk 1]
```diff
@@ -98,7 +98,7 @@ jasperreports_validate() {
         done
         is_empty_value "$JASPERREPORTS_SMTP_PORT_NUMBER" && print_validation_error "The JASPERREPORTS_SMTP_PORT_NUMBER environment variable is empty or not set."
         ! is_empty_value "$JASPERREPORTS_SMTP_PORT_NUMBER" && check_valid_port "JASPERREPORTS_SMTP_PORT_NUMBER"
-        ! is_empty_value "$JASPERREPORTS_SMTP_PROTOCOL" && check_multi_value "JASPERREPORTS_SMTP_PROTOCOL" "ssl tls"
+        ! is_empty_value "$JASPERREPORTS_SMTP_PROTOCOL" && check_multi_value "JASPERREPORTS_SMTP_PROTOCOL" "smtp ssl tls"
```
Comment (fmulero) [inline bitnami/jasperreports/8/debian-11/rootfs/opt/bitnami/scripts/libjasperreports.sh:101]: It seems there is another valid option `smtps`
```suggestion
        ! is_empty_value "$JASPERREPORTS_SMTP_PROTOCOL" && check_multi_value "JASPERREPORTS_SMTP_PROTOCOL" "smtp smtps ssl tls"
```

File: bitnami/jasperreports/README.md [hunk 2]
```diff
@@ -284,7 +284,7 @@ To configure JasperReports to send email using SMTP you can set the following en
 - `JASPERREPORTS_SMTP_PORT_NUMBER`: SMTP port.
 - `JASPERREPORTS_SMTP_USER`: SMTP account user.
 - `JASPERREPORTS_SMTP_PASSWORD`: SMTP account password.
-- `JASPERREPORTS_SMTP_PROTOCOL`: If specified, SMTP protocol to use. Allowed values: *tls*, *ssl*. No default.
+- `JASPERREPORTS_SMTP_PROTOCOL`: If specified, SMTP protocol to use. Allowed values: *smtp*, *tls*, *ssl*. Default: **smtp**.
```
Comment (fmulero) [inline bitnami/jasperreports/README.md:287]: It seems there is another valid option `smtps`
```suggestion
- `JASPERREPORTS_SMTP_PROTOCOL`: If specified, SMTP protocol to use. Allowed values: *smtp*, *smtps*, *tls*, *ssl*. Default: **smtp**.
```

**Review by fmulero — CHANGES_REQUESTED** [review]
Hi @grantemsley Thanks a lot for your contribution and sorry about my very late response.

I was checking some guides about how to configure the mail delivery and it seems there is another option `smtps` Could you add it?

**Review by fmulero — APPROVED** [review]
LGTM
