### PR TITLE
Remove airflow-worker.pid file

### LINKED ISSUE #15317: [bitnami/airflow-worker] Pidfile already exists
### Name and Version

bitnami/airflow-worker

### What steps will reproduce the bug?

Hello, I am getting following error:

`ERROR: Pidfile (/opt/bitnami/airflow/tmp/airflow-worker.pid) already exists. Seems we're already running? (pid: 1)`

I am running the Docker container on WSL and when I restart the PC then the error occurs. When I just delete the file manually then it starts working - it creates the same file again.

### What is the expected behavior?

_No response_

### What do you see instead?

`ERROR: Pidfile (/opt/bitnami/airflow/tmp/airflow-worker.pid) already exists. Seems we're already running? (pid: 1)`

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by lukasheinz92**
Remove airflow-worker.pid file if exists to prevent error after WSL restarts

Signed-off-by: lukasheinz92 <94646007+lukasheinz92@users.noreply.github.com>

### Applicable issues

  - fixes #15317

### CODE REVIEW

File: bitnami/airflow-worker/2/debian-11/rootfs/opt/bitnami/scripts/libairflowworker.sh [hunk 1]
```diff
@@ -46,6 +46,11 @@ airflow_worker_validate() {
 #   None
 #########################
 airflow_worker_initialize() {
+    # Remove airflow-worker.pid file if exists to prevent error after WSL restarts
+	if [ -f /opt/bitnami/airflow/tmp/airflow-worker.pid ]; then
```
Comment (mdhont) [inline bitnami/airflow-worker/2/debian-11/rootfs/opt/bitnami/scripts/libairflowworker.sh:50]: Could you fix the indentation of the if block?

**Review by mdhont — CHANGES_REQUESTED** [review]

File: bitnami/airflow-worker/2/debian-11/rootfs/opt/bitnami/scripts/libairflowworker.sh [hunk 2]
```diff
@@ -46,6 +46,11 @@ airflow_worker_validate() {
...
+		rm /opt/bitnami/airflow/tmp/airflow-worker.pid
+	fi
```
Comment (carrodher) [inline bitnami/airflow-worker/2/debian-11/rootfs/opt/bitnami/scripts/libairflowworker.sh:52]: It seems an issue using tabs VS spaces
```suggestion
    # Remove airflow-worker.pid file if exists to prevent error after WSL restarts
    if [ -f /opt/bitnami/airflow/tmp/airflow-worker.pid ]; then
        rm /opt/bitnami/airflow/tmp/airflow-worker.pid
    fi
```

File: bitnami/airflow-worker/2/debian-11/rootfs/opt/bitnami/scripts/libairflowworker.sh (hunk 1 above)
Comment (carrodher) [reply bitnami/airflow-worker/2/debian-11/rootfs/opt/bitnami/scripts/libairflowworker.sh:50]: It seems an issue using tabs VS spaces, lets fix it in the file directly so you can continue with the review and any internal test

**Review by mdhont — APPROVED** [review]
Lgtm!

File: bitnami/airflow-worker/2/debian-11/rootfs/opt/bitnami/scripts/libairflowworker.sh [hunk 3]
```diff
@@ -46,6 +46,11 @@ airflow_worker_validate() {
 #   None
 #########################
 airflow_worker_initialize() {
+    # Remove airflow-worker.pid file if exists to prevent error after WSL restarts
+    if [ -f /opt/bitnami/airflow/tmp/airflow-worker.pid ]; then
```
Comment (mdhont) [inline bitnami/airflow-worker/2/debian-11/rootfs/opt/bitnami/scripts/libairflowworker.sh:50]: @lukasheinz92, could you use $AIRFLOW_PID_FILE instead of using the path: For example 

```suggestion
    if [ -f $AIRFLOW_PID_FILE ]; then
        rm $AIRFLOW_PID_FILE
```

**Review by mdhont — CHANGES_REQUESTED** [review]

**Review by lukasheinz92 — COMMENTED** [review]
Now replaced with:
```
    if [ -f $AIRFLOW_PID_FILE ]; then
        rm $AIRFLOW_PID_FILE
    fi
```
Spaces used instead of tabs

File: bitnami/airflow-worker/2/debian-11/rootfs/opt/bitnami/scripts/libairflowworker.sh [hunk 4]
```diff
@@ -46,6 +46,11 @@ airflow_worker_validate() {
 #   None
 #########################
 airflow_worker_initialize() {
+    # Remove airflow-worker.pid file if exists to prevent error after WSL restarts
+    if [ -f $AIRFLOW_PID_FILE ]; then
```
Comment (mdhont) [inline bitnami/airflow-worker/2/debian-11/rootfs/opt/bitnami/scripts/libairflowworker.sh:50]: To prevent linter errors, could you use double quotes ? 
```suggestion
    if [ -f "$AIRFLOW_PID_FILE" ]; then
```

**Review by mdhont — CHANGES_REQUESTED** [review]

**Comment by lukasheinz92** [comment]
@mdhont I have added the double quotes as requested.

**Review by mdhont — APPROVED** [review]
