### PR TITLE
[bitnami/postgresql-repmgr]Add judge primary node ip port is itslef

### LINKED ISSUE #67372: [bitnami/postgresql-repmgr]  After a 3-node cluster, simultaneous restart of all nodes resulted in failure to start properly.
### Name and Version

bitnami/postgresql-repmgr:15.5.0-debian-11-r15

### What architecture are you using?

amd64

### What steps will reproduce the bug?

1. deploy a 3 node postgres cluster  in k8s v1.23, deploy in static pod mode
2. check it work right, there are one primary and two standby
3. stop postgres in each node, almost at the same time
4. check each postgres has stop
5. start each postgres, almost at the same time
6. check each postgres status 

### What is the expected behavior?

The postgres cluster can recover into healthz

### What do you see instead?

each pg pod in crash, can not election the primary

pg pod exit log
```
[2024-05-31 18:54:06] [ERROR] unable connect to upstream node (ID: 2337678), terminating
[2024-05-31 18:54:06] [HINT] upstream node must be running before repmgrd can start
[2024-05-31 18:54:06] [INFO] repmgrd terminating...
```

### Additional information

```
wal_log_hints = 'on'

reconnect_attempts='24'
reconnect_interval='5'

node_rejoin_timeout=300
```

### PR DESCRIPTION
**Pull request by kwenzh**
### Description of the change

It seems that the judgment of whether the master node IP is your own is missed here.

Updates the Bitnami postgres-repmgr librepmgr.sh , function `repmgr_get_primary_node`,  add  judgment of whether the master node IP is your own 
### Benefits

Optimize extreme abnormal scenarios, such as: cluster machines lose power at the same time, and the restored cluster self-healing

### Possible drawbacks

Whether the logic of repmgr itself has been tampered with

### Applicable issues

- fix: https://github.com/bitnami/containers/issues/67372

### Additional information

I'm happy to change approach if directed to how.

### CODE REVIEW

**Comment by kwenzh** [comment]
@fmulero @carrodher  please review this  pr

**Comment by kwenzh** [comment]
1

File: bitnami/postgresql-repmgr/15/debian-12/rootfs/opt/bitnami/scripts/librepmgr.sh [hunk 1]
```diff
@@ -237,8 +237,12 @@ repmgr_get_primary_node() {
...
             fi
         else
-            primary_host="$upstream_host"
-            primary_port="$upstream_port"
+           if  [[ "${upstream_host}:${upstream_port}" = "${REPMGR_NODE_NETWORK_NAME}:${REPMGR_PORT_NUMBER}" ]];  then
+                info "Skip Primary Ip self. Starting PostgreSQL normally..."
+           else
+                primary_host="$upstream_host"
+                primary_port="$upstream_port"
+           fi
```
Comment (fmulero) [inline bitnami/postgresql-repmgr/15/debian-12/rootfs/opt/bitnami/scripts/librepmgr.sh:245]:
```suggestion
            if  [[ "${upstream_host}:${upstream_port}" = "${REPMGR_NODE_NETWORK_NAME}:${REPMGR_PORT_NUMBER}" ]];  then
                info "Avoid setting itself as primary. Starting PostgreSQL normally..."
            else
                primary_host="$upstream_host"
                primary_port="$upstream_port"
            fi
```

**Review by fmulero — CHANGES_REQUESTED** [review]
Hi @kwenzh Sorry about my very late response. I loose this PR from my radar.

I left a little suggestion.

Anyway I'd like to review this change with @rafariossaa because I am not sure about the impact of this change

File: bitnami/postgresql-repmgr/15/debian-12/rootfs/opt/bitnami/scripts/librepmgr.sh (hunk 1 above)
Comment (kwenzh) [reply bitnami/postgresql-repmgr/15/debian-12/rootfs/opt/bitnami/scripts/librepmgr.sh:245]: OK just log notice, thank you

Comment (kwenzh) [reply bitnami/postgresql-repmgr/15/debian-12/rootfs/opt/bitnami/scripts/librepmgr.sh]: @rafariossaa  please look at this

**Comment by kwenzh** [comment]
refresh

**Review by fmulero — APPROVED** [review]
👍 LGTM
